Repository hmrc/tamc-frontend, pull requests merged in 2018-05, with the labels that each got.

#180 DDCNLS-1193 WIP
  app/controllers/LanguageController.scala
  app/utils/LanguageUtils.scala
  app/views/calculator.scala.html
  app/views/coc/bereavement_transferor.scala.html
  app/views/coc/change_in_earnings.scala.html
  app/views/coc/confirm.scala.html
  app/views/coc/confirm_updates.scala.html
  app/views/coc/email.scala.html
  app/views/coc/finished.scala.html
  app/views/coc/your_status.scala.html
  app/views/confirm.scala.html
  app/views/date_of_marriage.scala.html
  app/views/eligible_years.scala.html
  app/views/email.scala.html
  app/views/errors/session_timeout.scala.html
  app/views/finished.scala.html
  app/views/multi_year_select.scala.html
  app/views/multiyear/gds/date_of_birth_check.scala.html
  app/views/multiyear/gds/eligibility_check.scala.html
  app/views/multiyear/gds/lower_earner.scala.html
  app/views/multiyear/gds/partners_income_question.scala.html
  app/views/multiyear/pta/date_of_birth_check.scala.html
  app/views/multiyear/pta/eligibility_check.scala.html
  app/views/multiyear/pta/how_it_works.scala.html
  app/views/multiyear/pta/lower_earner.scala.html
  app/views/multiyear/pta/partners_income_question.scala.html
  app/views/pta/calculator.scala.html
  app/views/single_year_select.scala.html
  app/views/templates/lang_button.scala.html
  app/views/templates/tamc_main.scala.html
  app/views/transfer.scala.html
  conf/app.routes
  conf/application.conf
  project/build.properties
  test/controllers/LanguageControllerTest.scala
Labels: Review Completed

#181 Ddcnls 3390 TAMC - Create 'Do you live in Scotland' page
  app/controllers/LanguageController.scala
  app/controllers/MultiYearGdsEligibilityController.scala
  app/controllers/MultiYearPtaEligibilityController.scala
  app/forms/MultiYearDoYouLiveInScotlandForm.scala
  app/models/MultiYearDoYouLiveInScotlandFormInput.scala
  app/views/multiyear/gds/do_you_live_in_scotland.scala.html
  app/views/multiyear/gds/lower_earner.scala.html
  app/views/multiyear/pta/do_you_live_in_scotland.scala.html
  app/views/multiyear/pta/lower_earner.scala.html
  conf/app.routes
  conf/messages
  conf/messages.cy
  project/MicroService.scala
  project/plugins.sbt
  public/javascripts/tamc.js
  test/controllers/ContentTest.scala
  test/controllers/LanguageControllerTest.scala
  test/controllers/RoutesTest.scala
Labels: Ready for review

#185 Ddcnls 3479
  app/config/ApplicationConfig.scala
  app/controllers/BaseController.scala
  app/controllers/MultiYearGdsEligibilityController.scala
  app/controllers/MultiYearPtaEligibilityController.scala
  app/models/MultiYearDoYouLiveInScotlandFormInput.scala
  app/services/CachingService.scala
  app/utils/package.scala
  app/views/multiyear/gds/do_you_want_to_apply.scala.html
  app/views/multiyear/gds/partners_income_question.scala.html
  app/views/multiyear/pta/do_you_want_to_apply.scala.html
  app/views/multiyear/pta/partners_income_question.scala.html
  app/views/templates/form_error_notification.scala.html
  app/views/templates/input_radio_group.scala.html
  conf/app.routes
  conf/application.conf
  conf/messages
  conf/messages.cy
  test/controllers/AuthorisationControllerTest.scala
  test/controllers/BreadcrumbTest.scala
  test/controllers/ContentTest.scala
  test/controllers/EligibilityCalcControllerTest.scala
  test/controllers/ErrorsTest.scala
  test/controllers/LanguageControllerTest.scala
  test/controllers/MarriageAllowanceControllerTest.scala
  test/controllers/PtaEligibilityCalcControllerTest.scala
  test/controllers/RoutesTest.scala
  test/test_utils/TestUtility.scala
Labels: In Review
